### ISSUE TITLE
README.md dead links

### ISSUE THREAD

**Issue by xanthospap** [DSOlab/ggdatetime#3]
In the README.md file, the section [Precision](https://github.com/DSOlab/ggdatetime#precision) 
contains broken links (e.g. `This is verified by running the test program (unit_tests/tpdates2.cpp)[unit_tests/tpdates2.cpp]`). 
The links should work and point to the correct test files.

**Comment by naturalneuralnet** [comment]
I can fix this. New to contributing though.
